# Generated by Django 4.1.6 on 2023-02-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group_alter_account_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
