# Generated by Django 4.1.6 on 2023-02-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='account/microscope.png', upload_to='account'),
            preserve_default=False,
        ),
    ]
