# Generated by Django 4.1.6 on 2023-02-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='avatar',
        ),
    ]
