# Generated by Django 4.1.6 on 2023-04-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.AddField(
            model_name='activity',
            name='duration_in_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
