# Generated by Django 4.1.6 on 2023-04-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_activity', '0002_remove_activity_duration_activity_duration_in_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
