# Generated by Django 4.1.6 on 2023-02-11 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('extension_name', models.CharField(blank=True, max_length=50)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('municipality', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('O', 'Ongoing'), ('I', 'Inactive')], max_length=1)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('duration', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SALOG_Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('date_started', models.DateField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parameter.person')),
            ],
            options={
                'verbose_name': 'SALOG Employee',
                'verbose_name_plural': 'SALOG Employees',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('P', 'Primary Author'), ('S', 'Secondary Author')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
                ('SALOG_employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parameter.salog_employee')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('O', 'Ongoing'), ('I', 'Inactive')], max_length=1)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('duration', models.SmallIntegerField()),
                ('researcher', models.ManyToManyField(to='parameter.researcher')),
            ],
            options={
                'verbose_name_plural': 'Researches',
            },
        ),
    ]
