# Generated by Django 4.1.6 on 2023-02-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0002_news_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
