# Generated by Django 4.1.6 on 2023-02-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0003_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
