# Generated by Django 4.1.6 on 2023-02-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0006_remove_research_researcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.research')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.researcher')),
            ],
        ),
    ]
