# Generated by Django 4.1.6 on 2023-02-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0013_alter_researcherresearch_research'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResearcherResearch',
        ),
    ]
