# Generated by Django 4.1.6 on 2023-02-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0014_delete_researcherresearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='researcher',
            field=models.ManyToManyField(related_name='researchers', to='parameter.researcher'),
        ),
    ]
