# Generated by Django 4.1.6 on 2023-02-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0015_research_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
