# Generated by Django 4.1.6 on 2023-02-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0016_alter_project_date_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salog_employee',
            name='designation',
            field=models.CharField(choices=[('Prog. L', 'Program Leader'), ('Proj. L', 'Project Leader'), ('Proj. S', 'Project Staff')], max_length=7),
        ),
    ]
