# Generated by Django 4.1.6 on 2023-02-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0017_alter_salog_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='SALOG_employee',
            field=models.ManyToManyField(related_name='employees', to='parameter.salog_employee'),
        ),
    ]
