# Generated by Django 4.1.6 on 2023-02-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0018_project_salog_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salog_employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('Prog. L', 'Program Leader'), ('Proj. L', 'Project Leader'), ('Proj. S', 'Project Staff')], max_length=7, null=True),
        ),
    ]
