# Generated by Django 4.1.6 on 2023-02-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0019_alter_salog_employee_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='researcher',
        ),
        migrations.AddField(
            model_name='research',
            name='researchers',
            field=models.ManyToManyField(related_name='researches', to='parameter.researcher'),
        ),
    ]
