# Generated by Django 4.1.6 on 2023-02-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0020_remove_research_researcher_research_researchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='SALOG_employee',
        ),
        migrations.AddField(
            model_name='project',
            name='SALOG_employees',
            field=models.ManyToManyField(related_name='projects', to='parameter.salog_employee'),
        ),
    ]
