# Generated by Django 4.1.6 on 2023-02-16 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0021_remove_project_salog_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchResearcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.research')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.researcher')),
            ],
        ),
    ]
