# Generated by Django 4.1.6 on 2023-02-16 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0023_remove_research_researchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchresearcher',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researcher', to='parameter.researcher'),
        ),
    ]
