# Generated by Django 4.1.6 on 2023-02-16 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0028_alter_researchresearcher_research_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchresearcher',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_researcher', to='parameter.research'),
        ),
    ]
