# Generated by Django 4.1.6 on 2023-02-16 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0031_researcher_researcher_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='researcher_research',
        ),
    ]
