# Generated by Django 4.1.6 on 2023-02-16 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0032_remove_researcher_researcher_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchresearcher',
            name='researcher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parameter.researcher'),
            preserve_default=False,
        ),
    ]
