# Generated by Django 4.1.6 on 2023-02-16 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0033_researchresearcher_researcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='SALOG_employees',
        ),
    ]
