# Generated by Django 4.1.6 on 2023-02-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0035_projectemployee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='project_description',
        ),
    ]
