# Generated by Django 4.1.6 on 2023-04-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0037_coordinator_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='program',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='parameter.program'),
            preserve_default=False,
        ),
    ]
