# Generated by Django 4.1.6 on 2023-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0038_remove_program_coordinator_coordinator_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='SALOG_employees',
            field=models.ManyToManyField(related_name='projects', to='parameter.salog_employee'),
        ),
    ]
