# Generated by Django 4.1.6 on 2023-04-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0039_project_salog_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinator',
            old_name='address',
            new_name='agency_or_address',
        ),
    ]
