# Generated by Django 4.1.6 on 2023-04-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0040_rename_address_coordinator_agency_or_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='SALOG_employees',
        ),
    ]
