# Generated by Django 4.1.6 on 2023-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0042_salog_employee_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salog_employee',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='SALOG_employees',
            field=models.ManyToManyField(related_name='projects', to='parameter.salog_employee'),
        ),
    ]
