# Generated by Django 4.1.6 on 2023-04-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0043_remove_salog_employee_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='program',
        ),
    ]
