# Generated by Django 4.1.6 on 2023-04-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0044_remove_coordinator_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='coordinator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='parameter.coordinator'),
            preserve_default=False,
        ),
    ]
