# Generated by Django 4.1.6 on 2023-04-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0045_program_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salog_employee',
            name='date_started',
            field=models.DateField(auto_now_add=True),
        ),
    ]
