# Generated by Django 4.1.6 on 2023-04-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0047_alter_news_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='project',
        ),
        migrations.RemoveField(
            model_name='news',
            name='research',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
