# Generated by Django 4.1.6 on 2023-04-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0049_likagepartner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikagePartner',
            new_name='LinkagePartner',
        ),
    ]
