# Generated by Django 4.1.6 on 2023-04-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0050_rename_likagepartner_linkagepartner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkagepartner',
            options={'verbose_name': 'Linkage Partner', 'verbose_name_plural': 'Linkage Partners'},
        ),
        migrations.CreateModel(
            name='LinkagePartnerResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_linkage', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
                ('linkage_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.linkagepartner')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.research')),
            ],
        ),
    ]
