# Generated by Django 4.1.6 on 2023-04-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0051_alter_linkagepartner_options_linkagepartnerresearch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkagepartnerresearch',
            options={'verbose_name': 'Linkage Partner', 'verbose_name_plural': 'Linkage Partners'},
        ),
    ]
