# Generated by Django 4.1.6 on 2023-04-07 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0052_alter_linkagepartnerresearch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkagepartner',
            name='date_of_linkage',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LinkagePartnerResearch',
        ),
    ]
