# Generated by Django 4.1.6 on 2023-04-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0053_linkagepartner_date_of_linkage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='linkage_partner',
            field=models.ManyToManyField(related_name='linkage_researches', to='parameter.linkagepartner'),
        ),
    ]
