# Generated by Django 4.1.6 on 2023-04-08 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0055_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='research',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parameter.research'),
            preserve_default=False,
        ),
    ]
