# Generated by Django 4.1.6 on 2023-04-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0056_equipment_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='research',
        ),
    ]
