# Generated by Django 4.1.6 on 2023-04-08 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0057_remove_equipment_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parameter.equipment'),
            preserve_default=False,
        ),
    ]
