# Generated by Django 4.1.6 on 2023-04-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0060_remove_research_equipment_research_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkagepartner',
            name='logo',
            field=models.ImageField(
                default='+', upload_to='parameter/linkage_partner/image'),
            preserve_default=False,
        ),
    ]
