# Generated by Django 4.1.6 on 2023-04-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0061_linkagepartner_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='linkage_partner',
            new_name='linkage_partners',
        ),
        migrations.AlterField(
            model_name='linkagepartner',
            name='logo',
            field=models.ImageField(upload_to='parameter/linkage_partners/image'),
        ),
    ]
