# Generated by Django 4.1.6 on 2023-04-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0062_rename_linkage_partner_research_linkage_partners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
