# Generated by Django 4.1.6 on 2023-04-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0063_program_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
