# Generated by Django 4.1.6 on 2023-04-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0065_project_date_posted_project_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
