# Generated by Django 4.1.6 on 2023-04-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0066_research_date_posted_research_is_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'Research', 'verbose_name_plural': 'Researches'},
        ),
    ]
