# Generated by Django 4.1.6 on 2023-04-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0069_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='type',
            field=models.CharField(choices=[('F', 'Funding Agency'), ('I', 'Implementing Agency')], default='F', max_length=1),
            preserve_default=False,
        ),
    ]
