# Generated by Django 4.1.6 on 2023-04-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0071_alter_agency_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
    ]
