# Generated by Django 4.1.6 on 2023-04-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0072_alter_equipment_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SALOG_Employee',
            new_name='IRL_Employee',
        ),
        migrations.AlterModelOptions(
            name='irl_employee',
            options={'verbose_name': 'IRL Employee', 'verbose_name_plural': 'IRL Employees'},
        ),
    ]
