# Generated by Django 4.1.6 on 2023-04-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0073_rename_salog_employee_irl_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='SALOG_employees',
            new_name='IRL_employees',
        ),
        migrations.RenameField(
            model_name='researcher',
            old_name='SALOG_employee',
            new_name='IRL_employee',
        ),
    ]
