# Generated by Django 4.1.6 on 2023-04-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0074_rename_salog_employees_project_irl_employees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='equipments',
            new_name='equipment',
        ),
    ]
